services:
  jupyter:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/data
      - ./notebooks:/home/jovyan/notebooks
      - ./results:/home/jovyan/results
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PYSPARK_VERSION: "2.3.0"
      SPARK_HOME: "/usr/local/spark"
    command: start-notebook.sh --NotebookApp.token=''

  spark:
    image: bitnami/spark:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./results:/results
    environment:
      SPARK_MASTER_URL: "spark://spark-master:7077"